version: "3.9"

services:
  # Our postgres database
  db: # The service will be named db.
    image: postgres
    restart: always # Always try to restart if this stops running.
    environment: # Provide environment variables. Format VAR: value.
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports: # Exposing ports for apps outside the docker-compose.
      - "${DB_PORT}:5432" # Format is hostPort:containerPort <=> outside:inside.
        # postgres is listening in the container's 5432 port so we want to connect directly to there.

  # Adminer provides a nice web UI to connect to databases.
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Theme (https://github.com/vrana/adminer/tree/master/designs)
    ports: 
      - 3334:8080
