// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Preference struct {
	ID         int32        `json:"id"`
	Name       string       `json:"name"`
	Preference string       `json:"preference"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type RememberToken struct {
	ID            int32        `json:"id"`
	UserID        int32        `json:"user_id"`
	RememberToken string       `json:"remember_token"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID           int32         `json:"id"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	UserActive   sql.NullBool  `json:"user_active"`
	AccessLevel  sql.NullInt32 `json:"access_level"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	DeletedAt    sql.NullTime  `json:"deleted_at"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}
