// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	AllPreferences(ctx context.Context) ([]AllPreferencesRow, error)
	CheckForToken(ctx context.Context, arg CheckForTokenParams) (bool, error)
	DeleteToken(ctx context.Context, rememberToken string) error
	DeleteTokenByUserID(ctx context.Context, userID int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetTokenByID(ctx context.Context, arg GetTokenByIDParams) (GetTokenByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	InsertRememberMeToken(ctx context.Context, arg InsertRememberMeTokenParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) (int32, error)
	SetSystemPreference(ctx context.Context) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
