// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AllPreferences(ctx context.Context) ([]AllPreferencesRow, error)
	SetSystemPreference(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
